 

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'stock' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const CartItem = IDL.Record({
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
});
export const OrderItem = IDL.Record({
  'quantity' : IDL.Nat,
  'product' : Product,
});
export const OrderData = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'total' : IDL.Nat,
  'paymentMethod' : IDL.Text,
  'user' : IDL.Principal,
  'timestamp' : IDL.Int,
  'items' : IDL.Vec(OrderItem),
});

export const idlService = IDL.Service({
  'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'createOrder' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'createProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteOrder' : IDL.Func([IDL.Nat], [], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [OrderData], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
  'getUserOrders' : IDL.Func([], [IDL.Vec(OrderData)], ['query']),
  'initializeAdmin' : IDL.Func([], [], []),
  'removeFromCart' : IDL.Func([IDL.Nat], [], []),
  'searchProductsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'searchProductsByName' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'updateCartItem' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateProduct' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'stock' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const CartItem = IDL.Record({ 'productId' : IDL.Nat, 'quantity' : IDL.Nat });
  const OrderItem = IDL.Record({ 'quantity' : IDL.Nat, 'product' : Product });
  const OrderData = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'total' : IDL.Nat,
    'paymentMethod' : IDL.Text,
    'user' : IDL.Principal,
    'timestamp' : IDL.Int,
    'items' : IDL.Vec(OrderItem),
  });
  
  return IDL.Service({
    'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'createOrder' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'createProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteOrder' : IDL.Func([IDL.Nat], [], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getOrder' : IDL.Func([IDL.Nat], [OrderData], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
    'getUserOrders' : IDL.Func([], [IDL.Vec(OrderData)], ['query']),
    'initializeAdmin' : IDL.Func([], [], []),
    'removeFromCart' : IDL.Func([IDL.Nat], [], []),
    'searchProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'searchProductsByName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'updateCartItem' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateProduct' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };